# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
stages:
- stage: Build
  displayName: build artifact
  pool: ubuntu20
  variables:
    imageRepo: keoffor/reimburse
    tag: $(Build.BuildId)
  jobs:
  - job: build
    displayName: build maven/docker package

    steps:
    - task: SonarCloudPrepare@1
      displayName: Sonar Analysis
      inputs:
        SonarCloud: 'obaz-pro'
        organization: 'keoffor'
        scannerMode: 'Other'
        extraProperties: |
          # Additional properties that will be passed to the scanner,
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.projectKey=keoffor_reimbursementApi.git
          sonar.projectName=reimbursementApi.git

    - task: Maven@3
      displayName: Maven package
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        isJacocoCoverageReportXML: true
        sqMavenPluginVersionChoice: 'latest'
        
    - task: Maven@3
      displayName: publish coverage
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        codeCoverageToolOption: 'JaCoCo'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: true
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        isJacocoCoverageReportXML: true
        sqMavenPluginVersionChoice: 'latest'

    - task: Docker@2
      displayName: Build Docker image
      inputs:
        containerRegistry: 'docker-pro'
        repository: $(imageRepo)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(tag)
    - task: PublishPipelineArtifact@1
      displayName: Publish artifacts
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/Kubernetes'
        artifact: 'manifest'
        publishLocation: 'pipeline'
- stage: 
  displayName: Deploy to Dev.
  dependsOn: Build
  variables:
    acrsecret: obazsecret
    replicaNo: 2
  jobs:
  - deployment: deploy
    pool: ubuntu20
    displayName: Deploy to aks
    environment: 'obazenv.default'
    strategy:
     runOnce:
       deploy:  
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: download artifacts
            inputs:
              buildType: 'current'
              artifactName: 'manifest'
              targetPath: '$(Pipeline.Workspace)/manifest'
          - task: replacetokens@5
            inputs:
              rootDirectory: '$(Pipeline.Workspace)/manifest/'
              targetFiles: 'deployment.yml'
              encoding: 'auto'
              tokenPattern: 'custom'
              tokenPrefix: '#'
              tokenSuffix: '#'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              actionOnNoFiles: 'continue'
              enableTransforms: false
              enableRecursion: false
              useLegacyPattern: false
              enableTelemetry: true

          - task: KubernetesManifest@0
            displayName: authenticate pull request
            inputs:
              action: 'createSecret'
              kubernetesServiceConnection: 'obazenv-myAKSCluster-default-1652353003809'
              namespace: 'default'
              secretType: 'dockerRegistry'
              secretName: '$(acrsecret)'
              dockerRegistryEndpoint: 'docker-pro'
