#spring:
#  application:
#    name: reimbursementApi
#  datasource:
#    username: staging
#    password: Dreams16
#    url: jdbc:postgresql://35.192.86.45/stagedb
##      url: ${DB_URL:jdbc:postgresql://offorsql.postgres.database.azure.com/primerdb}
#
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#        format_sql: true
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#jwt:
#  secret: token_secret
#  expiry: 360000
#
#server:
#  port: 8002
#  servlet:
#    context-path: /
#
#api:
#  config:
#    api2-url: http://localhost:8001/email
spring:
  application:
    name: reimbursementApi
  datasource:
    username: root
    password: dreams20
    url: jdbc:mysql://localhost:3306/mydb
  #    driver-class-name: org.postgresql.Driver
  #  h2:
  #    console.enabled: true
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    username: sa
  #    password: password
  #    driverClassName: org.h2.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: true

    #    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
jwt:
  secret: token_secret
  expiry: 360000

server:
  port: 8080
api:
  config:
    api2-url: ${EMAIL_URL:http://localhost:8001}