---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reimburse-deployment
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: reimburse-app
  template:
    metadata:
      labels:
        app: reimburse-app
    spec:
      containers:
      - image: keoffor/reimburse-app
        env:
          - name: EMAIL_URL
            value: http://20.84.175.31:8001/email
        imagePullPolicy: Always
        name: reimburse-container
        ports:
        - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-app
  name: reimburse-service
spec:
  type: LoadBalancer
  ports:
    - name: service-https
      port: 8000
      targetPort: 8000
  selector:
    app: reimburse-app
